import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/contexts/ThemeContext";
import { ReduxProvider } from "@/providers/ReduxProvider";
import { AuthProvider } from "@/providers/AuthProvider";

import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const baseUrl = process.env.NEXT_PUBLIC_API_URL || 'https://www.learnityxai.corespace.click/';

export const metadata: Metadata = {
  title: "LearnityxAi",
  description: "Generated by create next app",
  metadataBase: new URL(baseUrl),
  icons: {
    icon: [
      { url: '/logo/logo.png', type: 'image/png' },
      { url: `${baseUrl}logo/logo.png`, type: 'image/png' },
    ],
    shortcut: '/logo/logo.png',
    apple: '/logo/logo.png',
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link rel="icon" href="/logo/logo.png" type="image/png" />
        <link rel="shortcut icon" href="/logo/logo.png" type="image/png" />
        <link rel="apple-touch-icon" href="/logo/logo.png" />
        {/* Blocking script to prevent flash and apply theme instantly */}
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  const storageKey = 'learnityx-theme';
                  const stored = localStorage.getItem(storageKey);
                  const theme = stored || (window.matchMedia('(prefers-color-scheme: dark)').matches ? 'dark' : 'light');
                  const root = document.documentElement;

                  // Add loading class to prevent transitions on initial load
                  root.classList.add('loading');

                  // Apply theme immediately
                  root.classList.add(theme);
                  root.setAttribute('data-theme', theme);

                  // Remove loading class after a brief moment to enable transitions
                  setTimeout(() => {
                    root.classList.remove('loading');
                  }, 50);
                } catch (e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ReduxProvider>
          <AuthProvider>
            <ThemeProvider>
              {children}
            </ThemeProvider>
          </AuthProvider>
        </ReduxProvider>

      </body>
    </html>
  );
}